// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://faqxqtsgqhqswnqxkrob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhcXhxdHNncWhxc3ducXhrcm9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MzAxNDAsImV4cCI6MjA2NjUwNjE0MH0.EPjCqrkEU9YdnywconcQ2UjhCuAeUsIkMajm-8FdgPc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);